import './globals.scss';

import React from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ProfileProvider } from '@/providers/ProfileProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<ProfileProvider>
				<body className={inter.className}>{children}</body>
			</ProfileProvider>
		</html>
	);
}
